# Generated by Django 3.0.3 on 2020-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemoresponse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetimage',
            name='baseline',
            field=models.BooleanField(default=False, verbose_name='baseline'),
        ),
    ]
