# Generated by Django 3.0.3 on 2020-03-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemoresponse', '0003_auto_20200313_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetimage',
            name='lesion_measure',
            field=models.FloatField(blank=True, null=True, verbose_name='Measure'),
        ),
    ]
