# Generated by Django 3.0.3 on 2020-03-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemoresponse', '0004_auto_20200313_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetimage',
            name='image_date',
        ),
    ]
